#Hexo theme zen
## Source: https://github.com/zxf/hexo-theme-zen

#Header
header:
  #set image and word
  logo:
    widgets:
      #- image
      - word
      - calendar
    calendar: solar
    image:
    color:
    word:
    content:

#Search engine
search: baidu

#Sidebar
sidebar:
- categories
- tags
- archives
#- links
#- projects

#Links
links:
  #hexo: http://hexo.io/

#Projects
projects:
  #hexo: http://hexo.io/

#Comments duoshuo|disqus
comment: disqus

#Share baidu|addthis
share: addthis

#Addthis info
addthis:
  pubid: 